# Use a imagem oficial do Node.js
FROM node:20

# Crie um diretório de trabalho
WORKDIR /app

# Copie os arquivos package.json e package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante dos arquivos do projeto
COPY . .

# Dê permissão ao script de inicialização
RUN chmod +x start.sh

# Exponha a porta que a aplicação utilizará
EXPOSE 3005

# Comando para executar o script de inicialização
CMD ["./start.sh"]
